name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  animated_splash_screen: ^1.3.0
  firebase_messaging: ^15.0.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/GymMatelogo-01.png"