// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxMP1dcsSMXySKyaahw-VQAN4uoeDsm2Q',
    appId: '1:683605958721:web:9ef01aed51b6fc147a26c0',
    messagingSenderId: '683605958721',
    projectId: 'xtrmgym-6ffcd',
    authDomain: 'xtrmgym-6ffcd.firebaseapp.com',
    storageBucket: 'xtrmgym-6ffcd.appspot.com',
    measurementId: 'G-M2CC3Q0EDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiVxTB2PyrPLtL6Hb6U9pciLVRQ9rQRIY',
    appId: '1:683605958721:android:0a58bea93eb0c54e7a26c0',
    messagingSenderId: '683605958721',
    projectId: 'xtrmgym-6ffcd',
    storageBucket: 'xtrmgym-6ffcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDum-Uiwe_XUKZA28uMb5SrL4usx4j3yeg',
    appId: '1:683605958721:ios:84482169ce8da7a37a26c0',
    messagingSenderId: '683605958721',
    projectId: 'xtrmgym-6ffcd',
    storageBucket: 'xtrmgym-6ffcd.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDum-Uiwe_XUKZA28uMb5SrL4usx4j3yeg',
    appId: '1:683605958721:ios:b9383bd3ee34ca697a26c0',
    messagingSenderId: '683605958721',
    projectId: 'xtrmgym-6ffcd',
    storageBucket: 'xtrmgym-6ffcd.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
